global function AttritionExtendedRecodePlaylistvars_Init

void function AttritionExtendedRecodePlaylistvars_Init()
{
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode", "piloted_titan_count", "3", "Piloted Titan Count" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode", "piloted_titan_ramp_up_score", "150", "Piloted Titan Ramp Up Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode", "unpiloted_titan_count", "0", "Unpiloted Titan Count" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode", "unpiloted_titan_ramp_up_score", "150", "Unpiloted Titan Ramp Up Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode", "titan_spawn_score", "650", "Titan Spawn Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode", "ct_titan_replace_chance", "0.20", "Custom Titan Replace Chance" )

	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_0_spectres", "0", "Defcon 0 Spectres" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_0_spectre_spawn_chance", "0", "Defcon 0 Spectre Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_0_stalkers", "0", "Defcon 0 Stalkers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_0_stalker_spawn_chance", "0", "Defcon 0 Stalker Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_0_reapers", "0", "Defcon 0 Reapers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_0_reaper_spawn_chance", "0", "Defcon 0 Reaper Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_0_additional_ai_slots", "0", "Defcon 0 Additional AI Slots" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_score", "125", "Defcon 1 Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_spectres", "4", "Defcon 1 Spectres" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_spectre_spawn_chance", "10", "Defcon 1 Spectre Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_stalkers", "0", "Defcon 1 Stalkers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_stalker_spawn_chance", "0", "Defcon 1 Stalker Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_reapers", "0", "Defcon 1 Reapers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_reaper_spawn_chance", "0", "Defcon 1 Reaper Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_1_additional_ai_slots", "0", "Defcon 1 Additional AI Slots" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_score", "250", "Defcon 2 Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_spectres", "12", "Defcon 2 Spectres" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_spectre_spawn_chance", "15", "Defcon 2 Spectre Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_stalkers", "0", "Defcon 2 Stalkers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_stalker_spawn_chance", "0", "Defcon 2 Stalker Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_reapers", "0", "Defcon 2 Reapers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_reaper_spawn_chance", "0", "Defcon 2 Reaper Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_2_additional_ai_slots", "0", "Defcon 2 Additional AI Slots" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_score", "330", "Defcon 3 Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_spectres", "12", "Defcon 3 Spectres" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_spectre_spawn_chance", "15", "Defcon 3 Spectre Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_stalkers", "4", "Defcon 3 Stalkers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_stalker_spawn_chance", "10", "Defcon 3 Stalker Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_reapers", "0", "Defcon 3 Reapers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_reaper_spawn_chance", "0", "Defcon 3 Reaper Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_3_additional_ai_slots", "0", "Defcon 3 Additional AI Slots" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_score", "500", "Defcon 4 Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_spectres", "12", "Defcon 4 Spectres" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_spectre_spawn_chance", "15", "Defcon 4 Spectre Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_stalkers", "4", "Defcon 4 Stalkers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_stalker_spawn_chance", "10", "Defcon 4 Stalker Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_reapers", "2", "Defcon 4 Reapers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_reaper_spawn_chance", "100", "Defcon 4 Reaper Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_4_additional_ai_slots", "2", "Defcon 4 Additional AI Slots" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_score", "575", "Defcon 5 Score" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_spectres", "12", "Defcon 5 Spectres" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_spectre_spawn_chance", "15", "Defcon 5 Spectre Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_stalkers", "4", "Defcon 5 Stalkers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_stalker_spawn_chance", "10", "Defcon 5 Stalker Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_reapers", "3", "Defcon 5 Reapers" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_reaper_spawn_chance", "100", "Defcon 5 Reaper Spawn Chance" )
	AddPrivateMatchModeSettingArbitrary( "Attrition Extended Recode Defcon", "defcon_5_additional_ai_slots", "3", "Defcon 5 Additional AI Slots" )
}
