#if !AIRBORNE_EXECUTIONS_THING
	global const ATTRITION_EXTENDED_RECODE_HAS_KARMA_AIRBORNE_EXECUTIONS = 0
#endif
#if AIRBORNE_EXECUTIONS_THING
	global const ATTRITION_EXTENDED_RECODE_HAS_KARMA_AIRBORNE_EXECUTIONS = 1
#endif